"""

Django settings for pa_arriba_project project.



Generated by 'django-admin startproject' using Django 5.2.4.



For more information on this file, see

https://docs.djangoproject.com/en/5.2/topics/settings/



For the full list of settings and their values, see

https://docs.djangoproject.com/en/5.2/ref/settings/

"""



import os  # Necesario para os.environ.get y para construir rutas

from pathlib import Path



try:

    import dj_database_url  # NECESARIO PARA LA CONEXION A POSTGRES (NO USADO POR AHORA)

except ModuleNotFoundError:

    dj_database_url = None





# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent





# Quick-start development settings - unsuitable for production

# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/





# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.environ.get(

    'DJANGO_SECRET_KEY',

    'django-insecure-b5rp4(515x-@2el5=6_&7*7b#2yw1(=ju_9olo02m(4_lzssuq'

)





# SECURITY WARNING: don't run with debug turned on in production!

# Ajuste seguro: en producciÃ³n define DJANGO_DEBUG=False

DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# --- CONFIGURACIÃN DE SEGURIDAD PARA HOSTS ---

ALLOWED_HOSTS = [

    ".run.app",

    "pa-arriba.com",

    "www.pa-arriba.com",

    "127.0.0.1",

    "localhost",

    "0.0.0.0",

]

# ---------------------------------------------









# -------------------------------------------------------

# CSRF (necesario en Cloud Run con proxy)

# -------------------------------------------------------

CSRF_TRUSTED_ORIGINS = [

    "https://pa-arriba.com",

    "https://www.pa-arriba.com",

    "https://*.run.app",

]





# URL base del proyecto (usada en sitemap y robots.txt)

SITE_URL = 'https://pa-arriba.com'





# Application definition

INSTALLED_APPS = [

    'jazzmin',

    'django.contrib.admin',

    'django.contrib.auth',

    'django.contrib.contenttypes',

    'django.contrib.sessions',

    'django.contrib.messages',

    'django.contrib.staticfiles',



    'core',

    'store',

    'blog',

    'ckeditor',

    'import_export',

    'termometro',
    'storages',

]





MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'whitenoise.middleware.WhiteNoiseMiddleware',



    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]





ROOT_URLCONF = 'pa_arriba_project.urls'





TEMPLATES = [

    {

        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [

            os.path.join(BASE_DIR, 'core', 'templates'),

            os.path.join(BASE_DIR, 'core', 'templates', 'core'),

        ],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.debug',

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],

        },

    },

]





WSGI_APPLICATION = 'pa_arriba_project.wsgi.application'





# -------------------------------------------------------

# Database

# -------------------------------------------------------

# PostgreSQL en produccion (DATABASE_URL via env var)

# SQLite como fallback local

DATABASE_URL = os.environ.get('DATABASE_URL')



if DATABASE_URL:

    DATABASES = {

        'default': dj_database_url.config(

            default=DATABASE_URL,

            conn_max_age=600

        )

    }

else:

    DATABASES = {

        "default": {

            "ENGINE": "django.db.backends.sqlite3",

            "NAME": BASE_DIR / "db.sqlite3",

        }

    }





# Password validation

AUTH_PASSWORD_VALIDATORS = [

    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},

    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},

    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},

    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},

]





# Internationalization

LANGUAGE_CODE = 'es-ec'



TIME_ZONE = 'America/Guayaquil'



USE_I18N = True

USE_TZ = True





# Static files

STATIC_URL = '/static/'



STATICFILES_DIRS = [

    os.path.join(BASE_DIR, 'core', 'static'),

]



STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')



# CAMBIO FECHA:2026-05-23|MOTIVO: Redirigir uploads a GCS para persistencia en Cloud Run
GCS_BUCKET_NAME = os.environ.get("GCS_BUCKET_NAME", "paarriba-media-ec")
GCS_DEFAULT_ACL = "publicRead"
GCS_QUERYSTRING_AUTH = False
GCS_FILE_OVERWRITE = False

STORAGES = {
    "default": {"BACKEND": "storages.backends.gcloud.GoogleCloudStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}





# Ignorar un sitemap estÃ¡tico si existiera en la carpeta de static

STATICFILES_IGNORE_PATTERNS = ['sitemaps/sitemap.xml']





DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'





# CAMBIO FECHA:2026-05-23|MOTIVO: Media servida desde GCS
MEDIA_URL = 'https://storage.googleapis.com/paarriba-media-ec/'





CKEDITOR_UPLOAD_PATH = 'uploads/'





CKEDITOR_CONFIGS = {

    'default': {

        'toolbar': 'full',

        'height': 400,

        'width': '100%',

        'extraPlugins': 'codesnippet,autogrow,clipboard,pastefromword',

        'autoGrow_minHeight': 200,

        'autoGrow_maxHeight': 800,

        'removePlugins': 'resize',

        'allowedContent': True,

        'htmlEncodeOutput': False,

        'entities': False,

        'fullPage': False,

        'basicEntities': False,

        'pasteFromWordRemoveFontStyles': False,

        'pasteFromWordRemoveStyles': False,

        'forcePasteAsPlainText': False,

        'enterMode': 1,       # CKEDITOR.ENTER_P

        'shiftEnterMode': 2, # CKEDITOR.ENTER_BR

        'codeSnippet_theme': 'default',

    },

}





# =======================================================

# CONFIGURACIÃN DE CORREO ELECTRÃNICO (GMAIL SMTP)

# =======================================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'

EMAIL_PORT = 587

EMAIL_USE_TLS = True



EMAIL_HOST_USER = 'luis.bracerog06@gmail.com'

EMAIL_HOST_PASSWORD = 'argllmaplpqxspfy'

DEFAULT_FROM_EMAIL = 'luis.bracerog06@gmail.com'

SERVER_EMAIL = 'luis.bracerog06@gmail.com'





# =======================================================

# Cloud Run / Google Frontend

# =======================================================

USE_X_FORWARDED_HOST = False

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')



print("=== DJANGO RUNTIME SETTINGS AUDIT ===")

print(f"DEBUG = {DEBUG}")

print(f"ALLOWED_HOSTS = {ALLOWED_HOSTS}")

print("====================================")





# =======================================================

# LOGGING FORZADO PARA DIAGNÃSTICO EN CLOUD RUN

# =======================================================

LOGGING = {

    "version": 1,

    "disable_existing_loggers": False,

    "handlers": {

        "console": {

            "class": "logging.StreamHandler",

        },

    },

    "root": {

        "handlers": ["console"],

        "level": "ERROR",

    },

}


# =======================================================
# JAZZMIN - Admin UI Moderno
# =======================================================
JAZZMIN_SETTINGS = {
    "site_title": "Pa'Arriba Admin",
    "site_header": "Pa'Arriba",
    "site_brand": "Pa'Arriba",
    "welcome_sign": "Bienvenido al panel de administración",
    "copyright": "Pa'Arriba 2026",
    "search_model": ["blog.Post", "blog.Prospecto"],
    "topmenu_links": [
        {"name": "Sitio Web", "url": "https://pa-arriba.com", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "blog.Post": "fas fa-newspaper",
        "blog.Prospecto": "fas fa-user-plus",
        "termometro.TermometroRespuesta": "fas fa-thermometer-half",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-success",
    "accent": "accent-teal",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-success",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}

