# Generated by Django 5.2.4 on 2026-06-04 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0007_alter_prospecto_options_remove_prospecto_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanaEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('asunto', models.CharField(max_length=300)),
                ('cuerpo', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada')], default='borrador', max_length=20)),
                ('total_enviados', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Campaña Email',
                'verbose_name_plural': 'Campañas Email',
            },
        ),
        migrations.CreateModel(
            name='EnvioEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_destino', models.CharField(max_length=254)),
                ('nombre_destino', models.CharField(max_length=200)),
                ('enviado', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='marketing.campanaemail')),
                ('prospecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_email', to='blog.prospecto')),
            ],
            options={
                'verbose_name': 'Envío Email',
                'verbose_name_plural': 'Envíos Email',
            },
        ),
    ]
