# Generated by Django 5.2.4 on 2025-07-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='Pa´Arriba Equipo', max_length=100, verbose_name='Autor'),
        ),
    ]
