# Generated by Django 6.0 on 2025-12-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dueño', models.CharField(max_length=100, verbose_name='Nombre del Dueño')),
                ('nombre_negocio', models.CharField(max_length=100, verbose_name='Nombre del Negocio')),
                ('telefono', models.CharField(max_length=20, verbose_name='WhatsApp/Teléfono')),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección o Ubicación')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('que_usa_hoy', models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Qué usa hoy?')),
                ('estado', models.CharField(choices=[('frio', '❄️ Frío'), ('caliente', '🔥 Caliente'), ('demo', '🎥 Demo Enviada'), ('seguimiento', '📞 Próximo Contacto'), ('cerrado', '✅ Cliente Ganado')], default='frio', max_length=20, verbose_name='Estado del Prospecto')),
                ('fecha_ultima_llamada', models.DateField(blank=True, null=True, verbose_name='Última Llamada')),
                ('acuerdo_1', models.TextField(blank=True, null=True, verbose_name='Acuerdo 1')),
                ('fecha_acuerdo_2', models.DateField(blank=True, null=True, verbose_name='Fecha Acuerdo 2')),
                ('acuerdo_2', models.TextField(blank=True, null=True, verbose_name='Acuerdo 2')),
                ('fecha_acuerdo_3', models.DateField(blank=True, null=True, verbose_name='Fecha Acuerdo 3')),
                ('acuerdo_3', models.TextField(blank=True, null=True, verbose_name='Acuerdo 3')),
                ('notas_generales', models.TextField(blank=True, null=True, verbose_name='Notas Generales')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prospecto CRM',
                'verbose_name_plural': 'Prospectos CRM',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
