# Generated by Django 5.2.4 on 2026-05-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_prospecto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prospecto',
            options={'ordering': ['-fecha_actualizacion'], 'verbose_name': 'Prospecto CRM', 'verbose_name_plural': 'Prospectos CRM'},
        ),
        migrations.RemoveField(
            model_name='prospecto',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='prospecto',
            name='fecha_acuerdo_2',
        ),
        migrations.RemoveField(
            model_name='prospecto',
            name='fecha_acuerdo_3',
        ),
        migrations.AddField(
            model_name='prospecto',
            name='canal_entrada',
            field=models.CharField(blank=True, choices=[('meta_ad1', 'Meta Ads — Ad 1 Carrusel Mermas'), ('meta_ad2', 'Meta Ads — Ad 2'), ('meta_ad3', 'Meta Ads — Ad 3'), ('meta_ad4', 'Meta Ads — Ad 4 Reel Fugas'), ('referido', 'Referido'), ('organico', 'Orgánico'), ('otro', 'Otro')], max_length=20, null=True, verbose_name='Canal de Entrada'),
        ),
        migrations.AddField(
            model_name='prospecto',
            name='dolor_principal',
            field=models.CharField(blank=True, choices=[('costos_ojo', '#1 No controla costos — trabaja al ojo'), ('mermas', '#2 Mermas y fugas de dinero'), ('inventario', '#3 Sin control de inventario'), ('facturacion', '#4 Facturación manual'), ('otro', 'Otro')], max_length=20, null=True, verbose_name='Dolor Principal'),
        ),
        migrations.AddField(
            model_name='prospecto',
            name='etapa',
            field=models.CharField(choices=[('e0', 'E0 — Sin contactar'), ('e1', 'E1 — Mensaje enviado, sin respuesta'), ('e2', 'E2 — Conversación activa'), ('e3', 'E3 — Demo agendada'), ('e4', 'E4 — Negociación'), ('congelador', 'Congelador — Reactivar en 30 días'), ('alianza', 'Alianza — Canal diferente'), ('perdido', 'Perdido — Sin respuesta'), ('cerrado', 'Cerrado — Cliente ganado')], default='e0', max_length=20, verbose_name='Etapa'),
        ),
        migrations.AddField(
            model_name='prospecto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prospecto',
            name='fecha_proxima_accion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha próxima acción'),
        ),
        migrations.AddField(
            model_name='prospecto',
            name='proxima_accion',
            field=models.TextField(blank=True, null=True, verbose_name='Próxima acción'),
        ),
        migrations.AddField(
            model_name='prospecto',
            name='ultima_respuesta',
            field=models.TextField(blank=True, null=True, verbose_name='Última respuesta recibida'),
        ),
        migrations.AddField(
            model_name='prospecto',
            name='ultimo_mensaje_enviado',
            field=models.TextField(blank=True, null=True, verbose_name='Último mensaje enviado'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ciudad / Ubicación'),
        ),
    ]
