# Generated by Django 5.2.4 on 2026-07-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_prospecto_options_remove_prospecto_estado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image_alt_text",
            field=models.CharField(
                blank=True,
                help_text="Describir la imagen para SEO. Ej: Tabla de costeo de seco de pollo con precios Ecuador 2026",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="keywords",
            field=models.CharField(
                blank=True,
                help_text="Separar por comas. Ej: costeo de recetas Ecuador, food cost, recetas estándar. Se usa en meta keywords y JSON-LD.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Máx 160 caracteres. Aparece en Google debajo del título. Incluir keyword principal.",
                max_length=160,
                null=True,
            ),
        ),
    ]
