# Generated by Django 5.2.4 on 2025-11-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TermometroRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=30)),
                ('tipo_negocio', models.CharField(max_length=60)),
                ('crece', models.CharField(max_length=60)),
                ('avanza', models.CharField(max_length=60)),
                ('mejora', models.CharField(max_length=60)),
                ('reemprende', models.CharField(max_length=60)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
