# Generated by Django 5.2.4 on 2025-11-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termometro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termometrorespuesta',
            name='fase_final',
            field=models.CharField(default='RE-EMPRENDE', help_text='Fase de la marca (CRECE, AVANZA, MEJORA, RE-EMPRENDE).', max_length=15),
        ),
        migrations.AddField(
            model_name='termometrorespuesta',
            name='puntaje_caos',
            field=models.IntegerField(default=0, help_text='Puntuación total del diagnóstico (Max. 16).'),
        ),
    ]
